packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  es5-ext: false
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@decadez/nest-infra@0.1.0"
  - "@decadez/nest-infra@0.2.0"
  - "@decadez/nest-infra@0.3.0"
